name: advanced_incident_response
steps:
  - action: firewall.block_ip
    params:
      ip: INCIDENT_SRC_IP
  - action: soar.response.actions.account.suspend_user_account
    params:
      user_id: INCIDENT_USER_ID
  - action: soar.response.actions.evidence.preserve_incident_evidence
    params:
      file_path: INCIDENT_EVIDENCE_PATH
  - action: soar.response.actions.ticket.create_ticket_action
    params:
      system: servicenow
      summary: INCIDENT_SUMMARY
      description: INCIDENT_DESCRIPTION
  - action: soar.response.actions.user_notify.notify_user_action
    params:
      user_id: INCIDENT_USER_EMAIL
      subject: INCIDENT_SUBJECT
      body: INCIDENT_BODY
  - action: soar.response.actions.config_verify.verify_config_action
    params:
      file_path: INCIDENT_CONFIG_PATH
  - action: soar.response.actions.patch.patch
    params:
      runbook: INCIDENT_RUNBOOK
      parameters: INCIDENT_PARAMETERS
  - action: soar.response.actions.recovery.restore_from_backup
    params:
      host: INCIDENT_HOST_ID
  - action: soar.response.actions.cloud.rollback_vm
    params:
      vm_id: INCIDENT_VM_ID
  - action: soar.response.actions.cloud.restore_service
    params:
      service_id: INCIDENT_SERVICE_ID
  - action: notify.siem
    params:
      level: critical
