name: notify_user
steps:
  - action: soar.response.actions.user_notify.notify_user_action
    params:
      user_id: INCIDENT_USER_EMAIL
      subject: INCIDENT_SUBJECT
      body: INCIDENT_BODY
  - action: notify.siem
    params:
      level: info
