name: "Restore From Backup"
description: "Service and data restoration procedure using backups with verification and hardening"
version: "1.0"
triggers:
  - incident_type: "system_failure"
  - incident_type: "data_breach"

steps:
  - name: "Notify Recovery Start"
    action: "alert.send_alert"
    params:
      severity: "high"
      recipients: ["soc@company.com", "ops@company.com"]

  - name: "Trigger Backup Snapshot"
    action: "cloud.trigger_vm_backup"
    params:
      vm_name: "INCIDENT_SOURCE_SYSTEM"

  - name: "Initiate VM Restore"
    action: "cloud.restore_vm_backup"
    params:
      vm_name: "INCIDENT_SOURCE_SYSTEM"

  - name: "Verify Configuration"
    action: "system.verify_configuration"
    params:
      host_id: "INCIDENT_SOURCE_SYSTEM"
      baseline: "CIS_Level1"

  - name: "Apply Hardening"
    action: "system.harden_system"
    params:
      host_id: "INCIDENT_SOURCE_SYSTEM"
      profile: "CIS_Hardening"

  - name: "Create Recovery Ticket"
    action: "alert.create_ticket"
    params:
      priority: "high"
      category: "recovery"
