from soar.integrations.Cloud import CloudProvider
from soar.integrations.Cloud import CloudManager

def rollback_vm(incident, vm_id: str):
    cloud = CloudProvider()
    return cloud.rollback_vm(vm_id)

# Exemplo de ação para restaurar serviço na nuvem
from soar.integrations.Cloud import CloudManager

def restore_service(incident, service_id: str):
    # Configure API URL e token conforme ambiente
    api_url = "https://management.azure.com"
    token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSIsImtpZCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNmJmZGIzMTgtOGRmYS00ZDRjLWFlNTUtYzA4NjJhYTZhNWIxLyIsImlhdCI6MTc1NjI1OTkwOSwibmJmIjoxNzU2MjU5OTA5LCJleHAiOjE3NTYyNjUwMzYsImFjciI6IjEiLCJhaW8iOiJBVVFBdS84WkFBQUFia2Z5cVJEODBSc2ppSkkyaERwRTlCdVNYT0J0M0VMbnEranBsQkdmQmlpa1dsS2FlQnIzUDVXWTh3cXA1WmloK2hJM09EYStJTlYvcjBIb3Q5Y2pEQT09IiwiYW1yIjpbInB3ZCIsInJzYSJdLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiZmVmNTRjOWMtYjM2Yi00NzQ1LTg3NmQtOGZkNDNhMGQxNDg5IiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiNDUuODcuMjEyLjE4NCIsIm5hbWUiOiJPc2NhciBSYWZhZWwgRGlhcyBSb2RyaWd1ZXMiLCJvaWQiOiI3YTQ3YWQyZi04YjgxLTQ1MGYtOGIxMS1kZGQ1YWJjYjAxZjUiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtNDI3OTY4MDYxMC0zMTA3NzY2NzEyLTMwODM1MTI2MTItMjA0OTEiLCJwdWlkIjoiMTAwMzIwMDE4Q0FBNjQ2NyIsInB3ZF91cmwiOiJodHRwczovL3BvcnRhbC5taWNyb3NvZnRvbmxpbmUuY29tL0NoYW5nZVBhc3N3b3JkLmFzcHgiLCJyaCI6IjEuQVhvQUdMUDlhX3FOVEUydVZjQ0dLcWFsc1VaSWYza0F1dGRQdWtQYXdmajJNQlBtQUZCNkFBLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInNpZCI6IjFlMmNiYmM2LTM0MDItNDYyZi04NGJhLWM3YTkyMWMyYmJlOSIsInN1YiI6ImhVaUp0RzhDa21NWXlJN2s0cHVwdkU4QWw1c1VGV1B1MjVjTmhXcjBKVjQiLCJ0aWQiOiI2YmZkYjMxOC04ZGZhLTRkNGMtYWU1NS1jMDg2MmFhNmE1YjEiLCJ1bmlxdWVfbmFtZSI6InB2MjMwMjBAYWx1bm9zLmVzdGd2Lmlwdi5wdCIsInVwbiI6InB2MjMwMjBAYWx1bm9zLmVzdGd2Lmlwdi5wdCIsInV0aSI6ImFLQklJTGM4SGs2TVZ2UklJVWdMQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfZnRkIjoiTE4weVBja2lpZVhWUXhqdFBiN2xXMVFSbHRveG8xMXlJa0Q1MTZ4bVRoSUJabkpoYm1ObFl5MWtjMjF6IiwieG1zX2lkcmVsIjoiMSAxNiIsInhtc190Y2R0IjoxNDYxNjgxNjg5fQ.hCxc3m-cQ7MhDTUyf9HqZzDaUQpPebPq1VXZCU9AQ2mAJDUyMDZWsYfWS5w1aP7adi_n7-XoronP0S7-h2Ul8MjARUBdiXRmo3WgPdfLg81kTQvrcxYm8nPXD_Mt20Co9o8mZSJtbdxjNR0nEd9n5k2mFlo4Fz3Qvgqf16yRwRCq4-Y1-nW2AquRwlKcj8ut0kF7itN992nC5sOfCIlj-OGsmBajT4f7APTfTzTUqmYawf6xkR019bmcKz6kAm0Gb-z6R2deOD47aYOkBcwJr2L-qaMF-hR0KCwApqCxcaeFs8A9Tjhc6x3OUGWa07OCxtUeNAQJFiz7L7Njh2rfKg"
    cloud_mgr = CloudManager(api_url, token)
    return cloud_mgr.restore_service(service_id)
