version: "3.9"

services:
  soar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soar
    command: uvicorn src.soar.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    working_dir: /14_Final
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - soar
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always